version: "3.9"
services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        stdin_open: true
        volumes:
            - /app/node_modules
            - ./frontend:/app/
        depends_on:
            - backend
        links:
            - backend
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile.dev
        volumes:
            - /app/node_modules/
            - ./backend/:/app/
        depends_on:
            database:
                condition: service_healthy
        links:
            - database
        entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
        restart: "always"
        environment:
            - PORT=3001
            - DB_HOST=database
            - DB_USERNAME=scrum_cards_user_1
            - DB_PASSWORD=123
            - DB_DATABASE=scrum_cards
            - DB_PORT=3306
            - WAIT_HOSTS=database
    database:
        image: mysql:5.7
        command: --init-file /data/application/init.sql
        volumes:
            - ./database/init.sql:/data/application/init.sql
        environment:
            MYSQL_DATABASE: scrum_cards
            MYSQL_USER: scrum_cards_user_1
            MYSQL_PASSWORD: 123
            MYSQL_PORT: 3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-uscrum_cards_user_1', '-p123']
            timeout: 20s
            retries: 10
    nginx:
        depends_on:
            - backend
            - frontend
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf