FROM node:10
WORKDIR /app
COPY ./backend/package.json /app
RUN npm install
RUN npm install -g nodemon --no-optional
RUN npm install -g sequelize-cli
RUN sequelize init
COPY ./backend /app
CMD [ "npm", "start.dev" ]